version: '3.8'

services:
  app:
    build:
      context: ./docker/app
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:stable
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8085:80"  # Changed default port 80 -> 8080
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"  # Changed default port 3306 -> 3308
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis:alpine
    container_name: redis_server
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"  # Changed default port 6379 -> 6380
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mysql_data: