version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - laravel

  web:
    image: nginx:1.28
    container_name: nginx-web
    restart: unless-stopped
    ports:
      - "8086:80"
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin-laravel
  #   depends_on:
  #     - mysql
  #   restart: unless-stopped
  #   ports:
  #     - "8087:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root

  #   networks:
  #     - laravel

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
